/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testF;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestTemplate {

    private Template template;

    @BeforeAll
    static void setUp() throws Exception {
        Template template = new Template("${one}, ${two}, ${three}");
        template.set("one", "1");
        template.set("two", "2");
        template.set("three", "3");
    }

    @Test
    void multipleVariables() throws Exception {
        assertTemplateEvaluatesTo("1, 2, 3");
    }

    @Test
    void unknownVariablesAreIgnored() throws Exception {
        template.set("doesnotexist", "whatever");
        assertTemplateEvaluatesTo("1, 2, 3");
    }

    @Test
    void assertTemplateEvaluatesTo(String expected) throws Exception {
        assertEquals(expected, template.evaluate());
    }
}
